services:
  # director-gateway-postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: director-gateway-development
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  director-registry-server:
    build:
      context: .
    ports:
      - "1112:1112"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:travel-china-spend-nothing@host.docker.internal:5432/director-registry-test
      PORT: 1112
    # depends_on:
    #   - director-gateway-postgres
    
# volumes:
#   postgres-data:
