# Director development environment
# If you are looking for the production docker image, please see: https://github.com/director-run/director-docker
name: director-development

services:
  postgres:
    image: postgres:17
    container_name: director-postgres
    environment:
      - POSTGRES_PASSWORD=travel-china-spend-nothing
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: